services:
  filter_transactions:
    container_name: filter_transactions
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/filter_mapper rabbitmq:5672 transactions
    volumes:
      - ./bin/filter_mapper:/app/bin/filter_mapper
    networks:
      - testing_net
    depends_on:
      - server