name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.4-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - testing_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5

  server:
    container_name: server
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./server_bin 0.0.0.0:9091 rabbitmq:5672
    volumes:
      - ./bin/server:/app/server_bin
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway:
    container_name: gateway
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/gateway 0.0.0.0:9090 server:9091
    volumes:
      - ./bin/gateway:/app/bin/gateway
    networks:
      - testing_net
    ports:
      - 9090:9090
    depends_on:
      - server

  filter_transactions1:
    container_name: filter_transactions1
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/filter_mapper rabbitmq:5672 transactions
    volumes:
      - ./bin/filter_mapper:/app/bin/filter_mapper
    networks:
      - testing_net
    depends_on:
      - server

  filter_transaction_items1:
    container_name: filter_transaction_items1
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/filter_mapper rabbitmq:5672 transaction_items
    volumes:
        - ./bin/filter_mapper:/app/bin/filter_mapper
    networks:
        - testing_net
    depends_on:
        - server

  filter_transaction_items2:
    container_name: filter_transaction_items2
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/filter_mapper rabbitmq:5672 transaction_items
    volumes:
        - ./bin/filter_mapper:/app/bin/filter_mapper
    networks:
        - testing_net
    depends_on:
        - server

networks:
  testing_net:
    driver: bridge
