name: tp1
include:
  - docker-compose-rabbit.yml
  - ./compose-files/docker-compose-client.yml
  - docker-compose-filter-transactions.yml
  - docker-compose-partial-aggregator3.yml
  
services:
  server: #no escala
    container_name: server
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./server_bin 0.0.0.0:9091 rabbitmq:5672
    volumes:
      - ./bin/server:/app/server_bin
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway: #no escala
    container_name: gateway
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/gateway 0.0.0.0:9090 server:9091
    volumes:
      - ./bin/gateway:/app/bin/gateway
    networks:
      - testing_net
    depends_on:
      - server

  filter_stores: #no escala
    container_name: filter_stores
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/filter_mapper rabbitmq:5672 stores
    volumes:
      - ./bin/filter_mapper:/app/bin/filter_mapper
    networks:
      - testing_net
    depends_on:
      - server

  concat: #no escala
    container_name: concat
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/concat rabbitmq:5672
    volumes:
      - ./bin/concat:/app/bin/concat
    networks:
      - testing_net
    depends_on:
      - server
      - rabbitmq
      # - filter_transactions

  global_aggregator3: #no escala
    container_name: global_aggregator3
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/global_aggregator rabbitmq:5672 query3Global
    volumes:
      - ./bin/global_aggregator:/app/bin/global_aggregator
    networks:
      - testing_net
    depends_on:
      - server
      - concat
      # - partial_aggregator3
  
  sender1: #no escala
    container_name: sender1
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/sender rabbitmq:5672 Query1
    volumes:
      - ./bin/sender:/app/bin/sender
    networks:
      - testing_net
    depends_on:
      - server
      - concat

  sender3: #no escala
    container_name: sender3
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/sender rabbitmq:5672 Query3
    volumes:
      - ./bin/sender:/app/bin/sender
    networks:
      - testing_net
    depends_on:
      - server
      - global_aggregator3
      - filter_stores

networks:
  testing_net:
    driver: bridge
