name: rabbit-test
services:
  rabbitmq:
    container_name: rabbitmq_test
    image: rabbitmq:4.1.4-management
    ports:
      - "5673:5672"   # AMQP (container 5672 → host 5673)
      - "15673:15672" # Management UI (container 15672 → host 15673)
    networks:
      - testing_net

networks:
  testing_net:
    driver: bridge
