services:
  client1:
    container_name: client1
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: sh -c "./bin/client ./dataset/ ./out/ gateway:9090 client1:9093 client1:9093" 
    volumes:
      - ../../bin/client:/app/bin/client
      - ../../dataset:/app/dataset
      - ../../out:/app/out
    depends_on:
      - gateway
    networks:
      - testing_net