services:
  client1:
    container_name: client1
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/client ./dataset/ ../out/ gateway:9090 host.docker.internal:9093
    volumes:
      - ../../bin/client:/app/bin/client
      - ../../dataset:/app/dataset
      - ../../out:/out
    depends_on:
      - gateway
    networks:
      - testing_net