services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.4-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - testing_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5

  server: #no escala
    container_name: server
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./server_bin 0.0.0.0:9091 rabbitmq:5672
    volumes:
      - ../../bin/server:/app/server_bin
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway: #no escala
    container_name: gateway
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/gateway 0.0.0.0:9090 server:9091
    volumes:
      - ../../bin/gateway:/app/bin/gateway
    networks:
      - testing_net
    ports:
      - 9090:9090
    depends_on:
      - server
