services:
  sender1: #no escala
    container_name: sender1
    image: ubuntu:24.04
    working_dir: /app
    entrypoint: ./bin/sender rabbitmq:5672 Query1
    volumes:
      - ../../bin/sender:/app/bin/sender
    networks:
      - testing_net
    depends_on:
      - server
      - concat