name: Test suite

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  lints:
    name: project lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: general sanity checks
        run: |
          make lint

  build-server:
    name: build-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build the server
        run: |
          make build-server

  build-client:
    name: build-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build the client
        run: |
          make build-client

  build:
    name: build
    # Run this job after the linter, so the cache is hot
    needs: [build-client, build-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          make build

  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check tests
        run: |
          make test
